version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mnu_events_postgres_prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mnu_events_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mnu_events_backend
    restart: always
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION}
      EMAIL_VERIFICATION_SECRET: ${EMAIL_VERIFICATION_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    depends_on:
      - postgres
    networks:
      - mnu_events_network

volumes:
  postgres_data:

networks:
  mnu_events_network:
    driver: bridge
