services:
  postgres:
    image: postgres:15-alpine
    container_name: mnu_events_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: mnu_user
      POSTGRES_PASSWORD: mnu_password
      POSTGRES_DB: mnu_events_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mnu_events_network

  # Просто запускаем postgres для локальной разработки
  # backend и frontend запускай вручную через npm run start:dev

volumes:
  postgres_data:

networks:
  mnu_events_network:
    driver: bridge
